### ISSUE TITLE
build deb installer

### ISSUE THREAD

**Issue by oussama-he** [oliverfindl/electron-vue-boilerplate#1]
How can I build deb installer for Linux using this boilerplate?

**Comment by oliverfindl** [comment]
Hello,

please refer to electron-builder [docs](https://www.electron.build/configuration/linux) to modify your `package.json` file according your needs.

If you have any questions, feel free to ask.

Thanks

**Comment by oussama-he** [comment]
Thank you.

**Comment by oliverfindl** [comment]
Closing this issue.
