### ISSUE TITLE
"Uncaught ReferenceError: require is not defined" when running "npm run dev"

### ISSUE THREAD

**Issue by Infinituum17** [oliverfindl/electron-vue-boilerplate#3]
![image](https://user-images.githubusercontent.com/40234342/100762036-d47d8f00-33f3-11eb-9f8e-21b22c344022.png)

**Comment by abjagtap** [comment]
any update? facing the same issue

**Comment by oliverfindl** [comment]
Hello,

Please look at [usage section in readme](https://github.com/oliverfindl/electron-vue-boilerplate#usage) and [this issue](https://github.com/oliverfindl/electron-vue-boilerplate/issues/2).

Thanks.
