### ISSUE TITLE
How to add custom title bar and menu like VS Code?

### ISSUE THREAD

**Issue by jigneshsuvariya** [oliverfindl/electron-vue-boilerplate#5]

**Comment by oliverfindl** [comment]
Hello,

don't want to be rude, but why are you asking here? You could just look at [VS Code](https://github.com/Microsoft/vscode) source yourself. Alternatively, you could / should ask that in [Electron](https://github.com/electron/electron) repo or even better, search in their [docs](https://www.electronjs.org/docs) beforehand. But to be helpful to you, I did one app like this, so the process is something in this lines as far as I remember (might have changed in some newer [Electron](repo) releases). You need to disable menu bar altogether in main process and create your own menu bar as part of your UI. There is some css property, that would manage drag of window and you need to pass close, maximize, minimize... actions via ipc to main process and handle them there.

Closing this issue, as it is not related to this repo at all.

Thanks.

**Comment by jigneshsuvariya** [comment]
Thanks for your word, will definitely look around to figure out how to set a custom title bar with a menu. 
Actually, I want to put this as a feature request but cannot figure out how to do that.

Thanks,

**Comment by oliverfindl** [comment]
Request denied, out of scope of this repo. This is just boilerplate repo, that should contain only minimal configuration / features.
