### ISSUE TITLE
Vue computed, data,.. properties not working?

### ISSUE THREAD

**Issue by hayr-hotoca** [oliverfindl/electron-vue-boilerplate#7]
Hi thanks for your work on this. I try data, computed properties in your code but it doesn't seem to work?

Here is the code:

![image](https://user-images.githubusercontent.com/21136244/123745382-6aba5a80-d8da-11eb-9687-21f8038bd494.png)

Here is the output: message2 is not displaying, and with computed property reversedMessage it is not returning even if I return a hard coded string

![image](https://user-images.githubusercontent.com/21136244/123745475-8887bf80-d8da-11eb-8036-1847647d2483.png)

Could you please help?

**Comment by oliverfindl** [comment]
Hello,

it looks like you are using composition API and legacy options API together. This boilerplate works only with composition API by default, but you can still enable legacy options API in [webpack.config.js](https://github.com/oliverfindl/electron-vue-boilerplate/blob/6b86a69adf1c9737aa7c4d6ac0499c9f1cb7e911/webpack-vue-app.config.js):

https://github.com/oliverfindl/electron-vue-boilerplate/blob/6b86a69adf1c9737aa7c4d6ac0499c9f1cb7e911/webpack-vue-app.config.js#L149

Let me know, if this helps you.

Thanks.

**Comment by hayr-hotoca** [comment]
Thanks it works now.
