### ISSUE TITLE
npm run dev throws an error

### ISSUE THREAD

**Issue by alexey-sh** [oliverfindl/electron-vue-boilerplate#8]
Node version: 16.5.0
NPM version: 7.19.1

`npm run dev` throws the following error:
```
ERROR in Cannot read config file: /Users/username/project/.eslintrc-vue-app.js
Error: Cannot find module '/Users/username/project/.eslintrc-vue-app.js'
Require stack:
- /Users/username/project/node_modules/@eslint/eslintrc/lib/noop.js

webpack 5.51.1 compiled with 1 error in 3464 ms
ℹ ｢wdm｣: Failed to compile.

```

If create `.eslintrc-vue-app.js` and `.eslintrc-electron-app.js` files with the following content
```
module.exports = {}
```
the `npm run dev` throws the following error

```
ERROR in 
/Users/username/project/src/vue-app/App.vue
  1:1  error  Parsing error: Unexpected token <

/Users/username/project/src/vue-app/components/HelloWorld.vue
  1:1  error  Parsing error: Unexpected token <

/Users/username/project/src/vue-app/main.js
  3:1  error  Parsing error: The keyword 'import' is reserved

✖ 3 problems (3 errors, 0 warnings)


webpack 5.51.1 compiled with 1 error in 1960 ms
ℹ ｢wdm｣: Failed to compile.

```

**Comment by oliverfindl** [comment]
Hello,

dunno why are you missing those files, but they are included in this repo. Perhaps you manually deleted them?
If you don't wish to use [eslint](https://github.com/eslint/eslint), you should update both [webpack](https://github.com/webpack/webpack) configs and remove [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin) together with other [eslint](https://github.com/eslint/eslint) dependencies.

If you have any more questions, feel free to ask here.

Thanks.

**Comment by oliverfindl** [comment]
Closing this issue.
